version: "3.8"

services:
    db:
        image: mysql:latest
        env_file:
            - ./db/db.env
        volumes:
            - ./db/mysql:/var/lib/mysql
        restart: on-failure
    api:
        build:
            context: ./api
            dockerfile: Dockerfile.dev
        env_file:
            - ./api/ormconfig-docker.env
        volumes:
            - ./api/src:/usr/app/src
        restart: on-failure
        depends_on:
            - db
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ./frontend/src:/usr/app/src
        env_file:
            - ./frontend/docker.env.development
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - 80:80
        depends_on:
            - frontend
            - api